<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>XboxControllerRemapper</AssemblyName>
    <RootNamespace>XboxControllerRemapper</RootNamespace>
    <StartupObject>XboxControllerRemapper.App</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpDX" Version="4.2.0" />
    <PackageReference Include="SharpDX.XInput" Version="4.2.0" />
    <PackageReference Include="InputSimulator" Version="1.0.4" />
  </ItemGroup>

</Project>
